config/routes.rb
Rails.application.routes.draw do
  get 'states' => 'country#all_states'

  get 'top_pop' => 'country#top_five_pop'

  get 'top_area' => 'country#top_five_area'

  root 'inventory#all_products'

  get 'show' => 'inventory#one_product'

  get 'category' => 'inventory#by_category'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/country_controller.rb
class CountryController < ApplicationController
  def all_states
  	@states = State.all
  end

  def top_five_pop
  	@states = State.order(population: :desc).limit(5)
  end

  def top_five_area
  	@states = State.order(area: :desc).limit(5)
  end
end

app/controllers/inventory_controller.rb
class InventoryController < ApplicationController
  def all_products
  	@products = Product.order(price: :desc)
  end

  def one_product
  	@product = Product.find(params[:id])
  end

  def by_category
  	@category = params[:category]
  	@products = Product.where(category: params[:category])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/country_helper.rb
module CountryHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/views/country/all_states.html.erb
<h1>All the States!</h1>
<small>(well...not all of them...)</small>

<p></p>

<table class="table">
	<tr>
		<th>Name</th>
		<th>Capital</th>
		<th>Population</th>
		<th>Area</th>
	</tr>
	<% @states.each do |state| %>
		<tr>
			<td>
				<%= state.name %>
			</td>
			<td>
				<%= state.capital %>
			</td>
			<td>
				<%= number_to_human(state.population) %>
			</td>
			<td>
				<%= number_with_delimiter(state.area) %> sq. mi.
			</td>
		</tr>
	<% end %>
</table>

app/views/country/top_five_area.html.erb
<h1>Top 5 States by Area</h1>


<table class="table">
	<tr>
		<th>Name</th>
		<th>Capital</th>
		<th>Population</th>
		<th>Area</th>
	</tr>
	<% @states.each do |state| %>
		<tr>
			<td>
				<%= state.name %>
			</td>
			<td>
				<%= state.capital %>
			</td>
			<td>
				<%= number_to_human(state.population) %>
			</td>
			<td>
				<%= number_with_delimiter(state.area) %> sq. mi.
			</td>
		</tr>
	<% end %>
</table>

app/views/country/top_five_pop.html.erb
<h1>Top 5 States by Population</h1>


<table class="table">
	<tr>
		<th>Name</th>
		<th>Capital</th>
		<th>Population</th>
		<th>Area</th>
	</tr>
	<% @states.each do |state| %>
		<tr>
			<td>
				<%= state.name %>
			</td>
			<td>
				<%= state.capital %>
			</td>
			<td>
				<%= number_to_human(state.population) %>
			</td>
			<td>
				<%= number_with_delimiter(state.area) %> sq. mi.
			</td>
		</tr>
	<% end %>
</table>

app/views/inventory/all_products.html.erb
<h1>Our Entire Inventory!</h1>

<table class="table">
	<tr>
		<th>Name</th>
		<th>Price</th>
		<th>Category</th>
	</tr>
	<% @products.each do |product| %>
		<tr>
			<td>
				<%= link_to product.name, show_path(id: product.id) %>
			</td>
			<td>
				<%= number_to_currency(product.price) %>
			</td>
			<td>
				<%= link_to product.category, category_path(category: product.category) %>
			</td>
		</tr>
	<% end %>
</table>

app/views/inventory/by_category.html.erb
<h1>All of Our <%= @category %> Items</h1>

<table class="table">
	<tr>
		<th>Name</th>
		<th>Price</th>
	</tr>
	<% @products.each do |product| %>
		<tr>
			<td>
				<%= link_to product.name, show_path(id: product.id) %>
			</td>
			<td>
				<%= number_to_currency(product.price) %>
			</td>
		</tr>
	<% end %>
</table>

app/views/inventory/one_product.html.erb
<div class="jumbotron">
	<h1><%= @product.name %></h1>
	<h3><%= number_to_currency @product.price %></h3>
	<h3><%= link_to @product.category, category_path(category: @product.category) %></h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FurnitureStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-default">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <%= link_to "Furniture", root_path, class: "navbar-brand" %>
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">
		      	<% if current_page?(states_path) %>
		        	<li class="active">
		        <% else %>
		        	<li>
		        <% end %>
		      	<%= link_to "All States", states_path %></li>
		      	<% if current_page?(top_pop_path) %>
		        	<li class="active">
		        <% else %>
		        	<li>
		        <% end %>
		      	<%= link_to "Top 5 Population", top_pop_path %></li>
		      	<% if current_page?(top_area_path) %>
		        	<li class="active">
		        <% else %>
		        	<li>
		        <% end %>
		      	<%= link_to "Top 5 Area", top_area_path %></li>
		        
		      </ul>
		    </div>
		  </div>
		</nav>

  	<div class="container">
	    <%= yield %>
  	</div>
  </body>
</html>